
[[navbar]]
    identifier = "home"
    name = "Home"
    url = "/"
     weight = 1

[[navbar]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

[[navbar]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3

[[navbar]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 4